import pyautogui,time

def getposition():
    for i in range(2):
        time.sleep(5)
        current_position = pyautogui.position()
        print(i,current_position)

def process():
    time.sleep(1)
    pyautogui.hotkey('alt','tab')
    pyautogui.hotkey('ctrl', 'tab')
    time.sleep(1)
    #for i in range(10):
    pyautogui.click(770,1000)
    pyautogui.write('hello,this and the above msg is generated by system',0.1)
    pyautogui.click(1844, 1022)

choice = int(input("1.Get position\n2.automate\n"))
match choice:
    case 1:
        getposition()

    case 2:
        process()

    case _:
        print("invalid input")